#!/usr/bin/env bash
# https://github.com/globaljindal

# -- OVERVIEW --
# Takes "sblu measure ftrmsd" for a set of FTFILES for a given LIG_FILE, LIG_CRYS, FTFILE and ROTPRM


# Set Up Folders/Files

# directory needs to include folders: FTFILE, rmsd (intermediate folder), output (output best rmsd)
# directory needs to include files: ROTPRM, LIG_FILE, and LIG_CRYS

FTFILE=~/Dropbox/PROTAC/data/ftfiles/*
ROTPRM=~/Dropbox/PROTAC/data/rot70k.0.0.4.prm
LIG_FILE=~/Dropbox/PROTAC/data/lig.pdb
LIG_CRYS=~/Dropbox/PROTAC/data/lig.pdb
rsmd=~/Dropbox/PROTAC/data/rmsd/*


# -- IMPORTANT --

# CHANGE OUTPUT FOLDER

output=~/Dropbox/PROTAC/data/lig02/


# Get RMSD for entire FT file

for f in $FTFILE
do
sblu measure ftrmsd -o ${f}_rmsd "$LIG_FILE" "$LIG_CRYS" "$f" "$ROTPRM"
mv ${f}_rmsd ./rmsd/
rm ${f}
done


# Get Best FT entries with a rmsd lower than FIVE

for i in $rsmd
do
nl -v0 ${i} | awk '{if ($2<5) print}' > ${i}_best
mv ${i}_best ${output}
rm ${i}
done

# script will remove files intermediate data and data for this iteration (to prepare for next set of rmsd analysis)

rm $LIG_FILE
rm $LIG_CRYS
rm $ROTPRM
